# Generated by Django 4.2.10 on 2024-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ref',
            field=models.CharField(blank=True, default='Нет ссылки', max_length=255),
        ),
    ]
