# Generated by Django 5.1.4 on 2024-12-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_book_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='logo',
            field=models.URLField(blank=True, default='https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Python.png', null=True),
        ),
    ]
